# Generated by Django 4.0.1 on 2022-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=250)),
                ('to_email', models.CharField(max_length=250)),
                ('crontab', models.CharField(max_length=70)),
                ('mail_text', models.TextField()),
                ('mail_subject', models.TextField()),
            ],
        ),
    ]
