# Generated by Django 4.0.1 on 2022-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=250)),
                ('crontab', models.CharField(max_length=70)),
                ('mail_text', models.TextField()),
                ('mail_subject', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='mail_subject',
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='mail_text',
        ),
        migrations.CreateModel(
            name='EmailRecipientsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('recipients', models.ManyToManyField(to='recipients.EmailRecipient')),
            ],
        ),
    ]
